[build]
  command = "npm install"
  publish = "functions"
  functions = "functions"

[[redirects]]
  from = "/projects"
  to = "/.netlify/functions/projects"
  status = 200

[[redirects]]
  from = "/projects/*"
  to = "/.netlify/functions/projects/:splat"
  status = 200

[[redirects]]
  from = "/tasks"
  to = "/.netlify/functions/tasks"
  status = 200

[[redirects]]
  from = "/tasks/*"
  to = "/.netlify/functions/tasks/:splat"
  status = 200

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
